.PHONY: all article presentation clean distclean

all: article presentation

article:
	$(MAKE) -C report

presentation:
	$(MAKE) -C presentation

clean:
	$(MAKE) -C report clean
	$(MAKE) -C presentation clean

distclean:
	$(MAKE) -C report distclean
	$(MAKE) -C presentation distclean
